package com.njcci.dao;

import com.njcci.dataobject.UserDO;
import org.springframework.stereotype.Repository;

@Repository
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njcci..user_info
     *
     * @mbg.generated Thu May 27 10:45:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njcci..user_info
     *
     * @mbg.generated Thu May 27 10:45:33 CST 2021
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njcci..user_info
     *
     * @mbg.generated Thu May 27 10:45:33 CST 2021
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njcci..user_info
     *
     * @mbg.generated Thu May 27 10:45:33 CST 2021
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njcci..user_info
     *
     * @mbg.generated Thu May 27 10:45:33 CST 2021
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njcci..user_info
     *
     * @mbg.generated Thu May 27 10:45:33 CST 2021
     */
    int updateByPrimaryKey(UserDO record);

    UserDO selectByTelphone(String telphone);

    UserDO selectByEmail(String email);
}